# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buffelist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire' 
  pod 'PopupDialog'
  pod 'RealmSwift'
  pod 'SkyFloatingLabelTextField'
  pod 'Cartography', '~> 3.0'

  target 'BuffelistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuffelistUITests' do
    # Pods for testing
  end

end
